# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BtcPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True, unique=True)),
                ('bit2c_price', models.FloatField(blank=True, null=True)),
                ('global_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'btc_price',
                'managed': False,
            },
        ),
    ]
